action_id: trunk-whoami
date: 2024-04-08 22:37:21
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1712615841
full_timestamp:
  nanos: 269917000
  seconds: 1712615841
trunk_version: 1.21.0
